#!/bin/bash
pdflatex "$1.tex"
bibtex "$1.aux"

## for multiple bib files
END=100
for ((i=1;i<=END;i++)); do
    FILE=$1$i-blx.aux
    if [ -f $FILE ]; then
	echo $FILE
	bibtex $FILE
    else
	break
    fi
done

pdflatex "$1.tex"
pdflatex "$1.tex"
